### PR TITLE
Nanos

### PR DESCRIPTION
**Pull request by nanosar90**
Wrote base html and css. Setup Tailwind as css framework.

### CODE REVIEW

**Review by n8blake — DISMISSED** [review]
Concerned about number of files. I don't know how to manage a node based project. Keep an eye on bugs.

**Review by sg3606 — DISMISSED** [review]
massive!

**Comment by n8blake** [comment]
Add files to .gitignore, resubmit pull request

**Review by n8blake — APPROVED** [review]
good

**Review by crichards17 — APPROVED** [review]

**Pull request merged**
